apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xgp5iojgs-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:991ecebe9b8179be512d21b74e27c3ac8d472628@sha256:b174b49cdf0c751cb8a61768fcea5a7d3cc9fcbe607716bf7feaa52891bd489d
          name: container-image
